const UI_PHRASES: Record<string, string> = {
  "about": "关于",
  "about the journal": "关于本刊",
  "all": "所有",
  "all web technology": "所有 Web 技术",
  "attributes": "属性",
  "blog": "博客",
  "css": "CSS（层叠样式表）",
  "css: styling language": "CSS（层叠样式表）：样式语言",
  "date & time formats": "日期与时间格式",
  "elements": "元素",
  "global attributes": "全局属性",
  "html": "HTML（超文本标记语言）",
  "html: markup language": "HTML（超文本标记语言）：标记语言",
  "html cheatsheet": "HTML 速查表",
  "html guides": "HTML 指南",
  "html reference": "HTML 参考",
  "javascript": "JavaScript（一种脚本语言）",
  "javascript: scripting language": "JavaScript（一种脚本语言）：脚本语言",
  "learn": "学习",
  "markup languages": "标记语言",
  "responsive images": "响应式图像",
  "see all": "查看全部",
  "see all…": "查看全部",
  "tools": "工具",
  "web apis": "Web APIs（网页应用程序接口）",
  "web apis: programming interfaces": "Web APIs（网页应用程序接口）：编程接口",
  "xml": "XML（可扩展标记语言）",
  "accept all cookies": "接受全部 Cookie",
  "access through your institution": "通过所在机构访问",
  "advertisement": "广告",
  "all journals": "所有期刊",
  "all subjects": "所有学科",
  "article": "文章",
  "articles": "文章",
  "author information": "作者信息",
  "back to top": "返回顶部",
  "browse issues": "浏览期刊",
  "cite this article": "引用本文",
  "close": "关闭",
  "content": "内容",
  "cookies": "Cookie",
  "download pdf": "下载 PDF",
  "explore content": "探索内容",
  "figures": "图表",
  "follow us": "关注我们",
  "for authors": "面向作者",
  "for referees": "面向审稿人",
  "get the most out of nature": "充分利用 Nature",
  "home": "首页",
  "global edition": "全球版",
  "asia": "亚洲",
  "china": "中国",
  "world": "世界",
  "business": "商业",
  "culture": "文化",
  "travel": "旅游",
  "video": "视频",
  "sports": "体育",
  "regional": "地方",
  "newspaper": "报纸",
  "mobile": "移动版",
  "global lens": "全球视角",
  "cartoons": "漫画",
  "editorials": "社论",
  "we comment": "我们评论",
  "opinion line": "意见热线",
  "asia-pacific pulse": "亚太脉搏",
  "global south voices": "全球南方之声",
  "journal information": "期刊信息",
  "languages": "语言",
  "log in": "登录",
  "manage preferences": "管理偏好",
  "menu": "菜单",
  "nature": "Nature",
  "news": "新闻",
  "open access": "开放获取",
  "opinion": "观点",
  "privacy policy": "隐私政策",
  "publish with us": "与我们合作出版",
  "published": "发布日期",
  "reject optional cookies": "拒绝可选 Cookie",
  "research": "研究",
  "research analysis": "研究分析",
  "research articles": "研究论文",
  "resources": "资源",
  "reviews": "评论",
  "rss feed": "RSS 订阅",
  "saved research": "已保存的研究",
  "search": "搜索",
  "search articles by subject, keyword or author": "按学科、关键词或作者搜索文章",
  "share": "分享",
  "show more": "显示更多",
  "show results from": "显示以下来源的结果",
  "sign in": "登录",
  "sign up": "注册",
  "sign up for alerts": "订阅提醒",
  "skip to main content": "跳转到主要内容",
  "subjects": "学科",
  "submit manuscript": "提交稿件",
  "subscribe": "订阅",
  "terms and conditions": "条款与条件",
  "this journal": "本刊",
  "view all": "查看全部",
  "view all journals": "查看所有期刊",
  "view issue": "查看本期",
  "your privacy, your choice": "你的隐私，你的选择",
};

export function normalizeUiPhrase(text: string): string {
  return text.replace(/\s+/g, " ").trim().toLocaleLowerCase();
}

/** Stable wording for common website chrome that small local models often miss. */
export function lookupLocalUiPhrase(text: string): string | undefined {
  return UI_PHRASES[normalizeUiPhrase(text)];
}
